export const mockSubreddits = [
  { id: 1, name: "Home", icon: "🏠", memberCount: 0, color: "bg-blue-500" },
  { id: 2, name: "Popular", icon: "🔥", memberCount: 0, color: "bg-red-500" },
  { id: 3, name: "Programming", icon: "💻", memberCount: 2400000, color: "bg-purple-500" },
  { id: 4, name: "React", icon: "⚛️", memberCount: 180000, color: "bg-blue-400" },
  { id: 5, name: "Web Development", icon: "🌐", memberCount: 650000, color: "bg-green-500" },
  { id: 6, name: "Design", icon: "🎨", memberCount: 520000, color: "bg-pink-500" },
  { id: 7, name: "Technology", icon: "📱", memberCount: 3100000, color: "bg-indigo-500" },
  { id: 8, name: "Startups", icon: "🚀", memberCount: 890000, color: "bg-orange-500" },
];

export const mockPosts = [
  {
    id: 1,
    title: "Just launched my first React project with Tailwind CSS!",
    content: "After weeks of learning, I finally built a functional todo app with authentication. The combination of React hooks and Tailwind utility classes made styling so much easier. Check it out and let me know what you think!",
    author: "CodeNewbie",
    subreddit: "React",
    upvotes: 2450,
    downvotes: 120,
    commentCount: 89,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=600&h=400&fit=crop",
  },
  {
    id: 2,
    title: "The future of web development is here",
    content: "With advances in edge computing, serverless architecture, and AI-assisted coding, the landscape of web development has changed dramatically. What are your thoughts on these trends?",
    author: "TechThoughts",
    subreddit: "Web Development",
    upvotes: 3120,
    downvotes: 200,
    commentCount: 156,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=400&fit=crop",
  },
  {
    id: 3,
    title: "UI Design patterns that every developer should know",
    content: "Exploring 5 critical UI patterns: Button states, Loading states, Error states, Empty states, and Confirmation dialogs. Each pattern plays a crucial role in user experience.",
    author: "DesignMaster",
    subreddit: "Design",
    upvotes: 4780,
    downvotes: 150,
    commentCount: 234,
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop",
  },
  {
    id: 4,
    title: "Building a sustainable tech startup in 2026",
    content: "Lessons learned from building a SaaS product from scratch. From MVP to Series A, here's what actually matters and what doesn't. Open to questions!",
    author: "StartupGuru",
    subreddit: "Startups",
    upvotes: 5610,
    downvotes: 180,
    commentCount: 287,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop",
  },
  {
    id: 5,
    title: "The complete guide to React Context API",
    content: "Everything you need to know about Context API, including when to use it, best practices, and how to avoid common pitfalls. Plus, performance tips!",
    author: "ReactExpert",
    subreddit: "React",
    upvotes: 6234,
    downvotes: 90,
    commentCount: 312,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    image: null,
  },
  {
    id: 6,
    title: "Why your mobile-first CSS is probably broken",
    content: "A deep dive into responsive design mistakes and how to fix them. Real examples from production code that went wrong.",
    author: "CSSWizard",
    subreddit: "Web Development",
    upvotes: 3450,
    downvotes: 240,
    commentCount: 198,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=400&fit=crop",
  },
  {
    id: 7,
    title: "AI is transforming how we code",
    content: "GitHub Copilot, ChatGPT, and other AI tools are changing software development. This is a game changer for productivity.",
    author: "TechEnthusiast",
    subreddit: "Programming",
    upvotes: 8900,
    downvotes: 450,
    commentCount: 567,
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1677442d019cecf8d424c73d60b0e1b0d5c5a5a?w=600&h=400&fit=crop",
  },
  {
    id: 8,
    title: "My journey from bootcamp to senior developer",
    content: "6 years ago I decided to switch careers. Here's what actually helped me become a senior engineer and what didn't matter at all.",
    author: "CareerChanger",
    subreddit: "Programming",
    upvotes: 7120,
    downvotes: 200,
    commentCount: 445,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    image: null,
  },
];

export const currentUser = {
  id: 1,
  username: "CurrentUser",
  avatar: "👤",
  karma: 12450,
  joinedDate: new Date("2020-03-15"),
  joinedSubreddits: [1, 2, 3, 4, 5],
};

// Mock comments with AI reasoning summaries (DS1-US1)
export const mockComments = [
  {
    id: 1,
    postId: 1,
    author: "ReactFan42",
    text: "Great post! Tailwind CSS has really changed how I approach styling. The utility-first approach reduces CSS bloat by 60% according to the 2025 State of CSS survey. Combined with React's component model, you get reusable, consistent UI without the hassle of naming conventions like BEM.",
    upvotes: 120,
    downvotes: 5,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    userVote: null,
    aiSummary: {
      summary: "Argues that Tailwind CSS's utility-first approach significantly reduces CSS bloat, citing the 2025 State of CSS survey as evidence.",
      primaryClaim: "Tailwind CSS reduces CSS bloat by 60% compared to traditional CSS approaches",
      evidenceBlocks: [
        { type: "study", content: "2025 State of CSS survey data on CSS bloat reduction", strength: "high" },
        { type: "anecdote", content: "Personal experience with component-based styling", strength: "medium" },
      ],
      coherenceScore: 0.87,
      generatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    },
  },
  {
    id: 2,
    postId: 1,
    author: "CSSPurist",
    text: "I disagree that Tailwind is always better. It clutters your HTML with dozens of classes and makes it harder to maintain large projects. Traditional CSS with proper architecture (like ITCSS or SMACSS) scales just as well. The survey data doesn't account for project complexity differences.",
    upvotes: 95,
    downvotes: 12,
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    userVote: null,
    aiSummary: {
      summary: "Counters the pro-Tailwind argument by claiming it reduces HTML readability and traditional CSS architectures scale equally well.",
      primaryClaim: "Traditional CSS architectures (ITCSS, SMACSS) scale as effectively as Tailwind for large projects",
      evidenceBlocks: [
        { type: "authority", content: "References established CSS methodologies (ITCSS, SMACSS)", strength: "medium" },
        { type: "other", content: "Critique of survey methodology not accounting for project complexity", strength: "low" },
      ],
      coherenceScore: 0.72,
      generatedAt: new Date(Date.now() - 50 * 60 * 1000),
    },
  },
  {
    id: 3,
    postId: 1,
    author: "FullStackDev",
    text: "Both approaches have merits. I've shipped production apps with both and the key factor is team familiarity, not the tool itself. What matters is consistency within the project. The real productivity gain from Tailwind comes from not context-switching between files.",
    upvotes: 78,
    downvotes: 2,
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    userVote: null,
    aiSummary: {
      summary: "Takes a balanced position, arguing that team familiarity and project consistency matter more than the specific CSS approach chosen.",
      primaryClaim: "Team familiarity is the key factor in CSS methodology effectiveness, not the tool itself",
      evidenceBlocks: [
        { type: "anecdote", content: "Personal experience shipping production apps with both approaches", strength: "medium" },
      ],
      coherenceScore: 0.91,
      generatedAt: new Date(Date.now() - 25 * 60 * 1000),
    },
  },
  {
    id: 4,
    postId: 2,
    author: "EdgeComputing",
    text: "Edge computing is the real game changer. Moving logic closer to users reduces latency by 40-70%. Cloudflare Workers and Deno Deploy are already proving this at scale. The serverless model works best when combined with edge, not as a standalone architecture.",
    upvotes: 210,
    downvotes: 15,
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    userVote: null,
    aiSummary: {
      summary: "Claims edge computing provides 40-70% latency reduction, citing Cloudflare Workers and Deno Deploy as evidence of viability at scale.",
      primaryClaim: "Edge computing reduces latency by 40-70% and is superior to standalone serverless",
      evidenceBlocks: [
        { type: "data", content: "40-70% latency reduction metric", strength: "medium" },
        { type: "authority", content: "Cloudflare Workers and Deno Deploy as production examples", strength: "high" },
      ],
      coherenceScore: 0.83,
      generatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    },
  },
  {
    id: 5,
    postId: 2,
    author: "AISkeptic",
    text: "AI-assisted coding is overhyped. These tools generate plausible-looking code that passes initial tests but introduces subtle bugs. Studies from Microsoft Research show that AI-generated code has 40% more security vulnerabilities. We're trading short-term speed for long-term technical debt.",
    upvotes: 185,
    downvotes: 45,
    timestamp: new Date(Date.now() - 3.5 * 60 * 60 * 1000),
    userVote: null,
    aiSummary: {
      summary: "Argues AI coding tools are overhyped, citing Microsoft Research data showing 40% more security vulnerabilities in AI-generated code.",
      primaryClaim: "AI-assisted coding introduces more security vulnerabilities and creates technical debt",
      evidenceBlocks: [
        { type: "study", content: "Microsoft Research study on AI-generated code security vulnerabilities", strength: "high" },
        { type: "other", content: "Trade-off argument between short-term speed and long-term debt", strength: "medium" },
      ],
      coherenceScore: 0.88,
      generatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    },
  },
  {
    id: 6,
    postId: 3,
    author: "UXResearcher",
    text: "Empty states are the most overlooked pattern here. A well-designed empty state can increase feature adoption by 30%. It's the first thing new users see and it sets the tone for the entire experience. I'd add onboarding patterns as a sixth essential pattern.",
    upvotes: 156,
    downvotes: 8,
    timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000),
    userVote: null,
    aiSummary: {
      summary: "Highlights empty states as the most critical underused UI pattern, claiming 30% improvement in feature adoption with proper implementation.",
      primaryClaim: "Well-designed empty states increase feature adoption by 30%",
      evidenceBlocks: [
        { type: "data", content: "30% feature adoption increase from empty state design", strength: "medium" },
        { type: "other", content: "Suggestion to add onboarding as a sixth pattern", strength: "low" },
      ],
      coherenceScore: 0.79,
      generatedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    },
  },
];

// Mock writing feedback data (DS3-US3)
export const mockWritingFeedback = {
  sampleDraft: "I think React is the best framework because everyone uses it. Plus, it's fast because it uses a virtual DOM, which I already mentioned. All developers prefer React over other frameworks.",
  feedback: {
    issues: [
      {
        id: 1,
        type: "weak_evidence",
        position: { start: 0, end: 62 },
        lineNumber: 1,
        flaggedText: "I think React is the best framework because everyone uses it",
        explanation: "Appeal to popularity — 'everyone uses it' is not evidence of quality. Cite specific metrics like npm downloads, GitHub stars, or benchmark comparisons.",
        severity: "medium",
        confidence: 0.85,
      },
      {
        id: 2,
        type: "circular_logic",
        position: { start: 100, end: 135 },
        lineNumber: 1,
        flaggedText: "which I already mentioned",
        explanation: "This repeats a point already made earlier in the draft without adding new information or evidence.",
        severity: "medium",
        confidence: 0.82,
      },
      {
        id: 3,
        type: "unsupported_claim",
        position: { start: 137, end: 195 },
        lineNumber: 1,
        flaggedText: "All developers prefer React over other frameworks",
        explanation: "Absolute claim without evidence. The State of JS survey shows React at ~40% usage, not universal preference.",
        severity: "high",
        confidence: 0.91,
      },
    ],
    score: 0.35,
    suggestions: [
      {
        id: 1,
        text: "Add specific data to support your claim about React's popularity",
        type: "reference",
        priority: "high",
        exampleFix: "'According to the 2025 State of JS survey, React is used by 40% of developers...'",
      },
      {
        id: 2,
        text: "Remove the repeated argument or expand with new supporting evidence",
        type: "structure",
        priority: "medium",
        exampleFix: "Instead of repeating the virtual DOM point, explain HOW it improves performance with benchmarks",
      },
      {
        id: 3,
        text: "Avoid absolute claims — qualify your statement",
        type: "clarity",
        priority: "high",
        exampleFix: "'Many developers prefer React for its ecosystem...' instead of 'All developers prefer...'",
      },
    ],
    goodPoints: [
      "Clear assertion of main position",
      "Mentions a specific technical feature (virtual DOM)",
    ],
    confidence: 0.79,
    generatedAt: new Date(),
  },
};
