export const mockSubreddits = [
  { id: 1, name: "Home", icon: "🏠", memberCount: 0, color: "bg-blue-500" },
  { id: 2, name: "Popular", icon: "🔥", memberCount: 0, color: "bg-red-500" },
  { id: 3, name: "Programming", icon: "💻", memberCount: 2400000, color: "bg-purple-500" },
  { id: 4, name: "React", icon: "⚛️", memberCount: 180000, color: "bg-blue-400" },
  { id: 5, name: "Web Development", icon: "🌐", memberCount: 650000, color: "bg-green-500" },
  { id: 6, name: "Design", icon: "🎨", memberCount: 520000, color: "bg-pink-500" },
  { id: 7, name: "Technology", icon: "📱", memberCount: 3100000, color: "bg-indigo-500" },
  { id: 8, name: "Startups", icon: "🚀", memberCount: 890000, color: "bg-orange-500" },
];

export const mockPosts = [
  {
    id: 1,
    title: "Just launched my first React project with Tailwind CSS!",
    content: "After weeks of learning, I finally built a functional todo app with authentication. The combination of React hooks and Tailwind utility classes made styling so much easier. Check it out and let me know what you think!",
    author: "CodeNewbie",
    subreddit: "React",
    upvotes: 2450,
    downvotes: 120,
    commentCount: 89,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=600&h=400&fit=crop",
  },
  {
    id: 2,
    title: "The future of web development is here",
    content: "With advances in edge computing, serverless architecture, and AI-assisted coding, the landscape of web development has changed dramatically. What are your thoughts on these trends?",
    author: "TechThoughts",
    subreddit: "Web Development",
    upvotes: 3120,
    downvotes: 200,
    commentCount: 156,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=400&fit=crop",
  },
  {
    id: 3,
    title: "UI Design patterns that every developer should know",
    content: "Exploring 5 critical UI patterns: Button states, Loading states, Error states, Empty states, and Confirmation dialogs. Each pattern plays a crucial role in user experience.",
    author: "DesignMaster",
    subreddit: "Design",
    upvotes: 4780,
    downvotes: 150,
    commentCount: 234,
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop",
  },
  {
    id: 4,
    title: "Building a sustainable tech startup in 2026",
    content: "Lessons learned from building a SaaS product from scratch. From MVP to Series A, here's what actually matters and what doesn't. Open to questions!",
    author: "StartupGuru",
    subreddit: "Startups",
    upvotes: 5610,
    downvotes: 180,
    commentCount: 287,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop",
  },
  {
    id: 5,
    title: "The complete guide to React Context API",
    content: "Everything you need to know about Context API, including when to use it, best practices, and how to avoid common pitfalls. Plus, performance tips!",
    author: "ReactExpert",
    subreddit: "React",
    upvotes: 6234,
    downvotes: 90,
    commentCount: 312,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    image: null,
  },
  {
    id: 6,
    title: "Why your mobile-first CSS is probably broken",
    content: "A deep dive into responsive design mistakes and how to fix them. Real examples from production code that went wrong.",
    author: "CSSWizard",
    subreddit: "Web Development",
    upvotes: 3450,
    downvotes: 240,
    commentCount: 198,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=400&fit=crop",
  },
  {
    id: 7,
    title: "AI is transforming how we code",
    content: "GitHub Copilot, ChatGPT, and other AI tools are changing software development. This is a game changer for productivity.",
    author: "TechEnthusiast",
    subreddit: "Programming",
    upvotes: 8900,
    downvotes: 450,
    commentCount: 567,
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    image: "https://images.unsplash.com/photo-1677442d019cecf8d424c73d60b0e1b0d5c5a5a?w=600&h=400&fit=crop",
  },
  {
    id: 8,
    title: "My journey from bootcamp to senior developer",
    content: "6 years ago I decided to switch careers. Here's what actually helped me become a senior engineer and what didn't matter at all.",
    author: "CareerChanger",
    subreddit: "Programming",
    upvotes: 7120,
    downvotes: 200,
    commentCount: 445,
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    image: null,
  },
];

export const currentUser = {
  id: 1,
  username: "CurrentUser",
  avatar: "👤",
  karma: 12450,
  joinedDate: new Date("2020-03-15"),
  joinedSubreddits: [1, 2, 3, 4, 5],
};
